### PR TITLE
Use ruby's memcpy macro in native extension

### LINKED ISSUE #31: Gem does not compile on Centos7 using Ruby 2.7.0
I'm unable to compile seven_zip_ruby on ruby 2.7.0.  It works fine on 2.5.x and 2.6.x on the same machine.  Also works on 2.7.0 on mac.  I haven't tried any other linux distributions.

Relevant failure message:
```
seven_zip_archive.cpp: In lambda function:
seven_zip_archive.cpp:1539:13: error: ‘ruby_nonempty_memcpy’ is not a member of ‘std’
             std::memcpy(data, RSTRING_PTR(str), RSTRING_LEN(str));
             ^
seven_zip_archive.cpp:1539:13: note: suggested alternative:
In file included from /var/jenkins/.rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/ruby.h:33:0,
                 from seven_zip_archive.h:27,
                 from seven_zip_archive.cpp:10:
/var/jenkins/.rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/ruby/ruby.h:1758:1: note:   ‘ruby_nonempty_memcpy’
 ruby_nonempty_memcpy(void *dest, const void *src, size_t n)
 ^
make: *** [seven_zip_archive.o] Error 1

make failed, exit code 2
```

### PR DESCRIPTION
**Pull request by Renerte**
Closes #31

On Linux compiler overrides standard `std::memcpy` function, which code references, with Ruby's `memcpy` macro, as such failing to resolve.

### CODE REVIEW

**Comment by xTRiM** [comment]
@masamitsu-murase can you please merge this?

**Comment by masamitsu-murase** [comment]
Thank you very much.
I'm really sorry for my late response.

**Comment by masamitsu-murase** [comment]
I released [seven_zip_ruby 1.3.0](https://rubygems.org/gems/seven_zip_ruby/versions/1.3.0), which includes your contribution.

Thank you so much!

**Comment by esdrash** [comment]
@masamitsu-murase,
I want to build a developpement_app, ruby version 3.0.2, on [docker alpine](https://github.com/docker-library/ruby/blob/4955e524a9a01f35979d7b7984a001fd563d5cfb/3.0/alpine3.16/Dockerfile), seven_zip_ruby (~> 1.3) always raises the errors in the screen shot.

image
